# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stegnar.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstegnar.proto\x12\x07stegnar\"\xc6\x01\n\x0cPayloadChunk\x12\x13\n\x0b\x65ndpoint_id\x18\x01 \x01(\t\x12\x11\n\tstream_id\x18\x02 \x01(\t\x12\x11\n\traw_bytes\x18\x03 \x01(\x0c\x12\x0e\n\x06sha256\x18\x04 \x01(\t\x12\x12\n\nssl_keylog\x18\x05 \x01(\t\x12\x0e\n\x06src_ip\x18\x06 \x01(\t\x12\x0e\n\x06\x64st_ip\x18\x07 \x01(\t\x12\x10\n\x08src_port\x18\x08 \x01(\r\x12\x10\n\x08\x64st_port\x18\t \x01(\r\x12\x13\n\x0b\x63\x61ptured_at\x18\n \x01(\x03\"=\n\tStreamAck\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x13\n\x0b\x63hunks_recv\x18\x02 \x01(\x04\x12\x0f\n\x07message\x18\x03 \x01(\t\"~\n\x0f\x41nalysisRequest\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x13\n\x0bimage_bytes\x18\x02 \x01(\x0c\x12\x0e\n\x06sha256\x18\x03 \x01(\t\x12\x13\n\x0b\x65ndpoint_id\x18\x04 \x01(\t\x12\x0e\n\x06src_ip\x18\x05 \x01(\t\x12\x0e\n\x06\x64st_ip\x18\x06 \x01(\t\"\x92\x01\n\x0e\x41nalysisResult\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x0f\n\x07verdict\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x11\n\traw_score\x18\x04 \x01(\x02\x12\x12\n\nmodel_type\x18\x05 \x01(\t\x12\x12\n\nlatency_ms\x18\x06 \x01(\r\x12\r\n\x05\x65rror\x18\x07 \x01(\t2O\n\rRouterService\x12>\n\rStreamPayload\x12\x15.stegnar.PayloadChunk\x1a\x12.stegnar.StreamAck\"\x00(\x01\x32V\n\x0f\x41nalysisService\x12\x43\n\x0c\x41nalyzeImage\x12\x18.stegnar.AnalysisRequest\x1a\x17.stegnar.AnalysisResult\"\x00\x42\x03\x90\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stegnar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\220\001\001'
  _globals['_PAYLOADCHUNK']._serialized_start=27
  _globals['_PAYLOADCHUNK']._serialized_end=225
  _globals['_STREAMACK']._serialized_start=227
  _globals['_STREAMACK']._serialized_end=288
  _globals['_ANALYSISREQUEST']._serialized_start=290
  _globals['_ANALYSISREQUEST']._serialized_end=416
  _globals['_ANALYSISRESULT']._serialized_start=419
  _globals['_ANALYSISRESULT']._serialized_end=565
  _globals['_ROUTERSERVICE']._serialized_start=567
  _globals['_ROUTERSERVICE']._serialized_end=646
  _globals['_ANALYSISSERVICE']._serialized_start=648
  _globals['_ANALYSISSERVICE']._serialized_end=734
_builder.BuildServices(DESCRIPTOR, 'stegnar_pb2', _globals)
# @@protoc_insertion_point(module_scope)
