FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    tshark \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY routing-system/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy proto stubs
COPY proto /app/proto

# Copy routing source
COPY routing-system/ /app/

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

EXPOSE 50051

CMD ["python", "main.py"]
