# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import stegnar_pb2 as stegnar__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in stegnar_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class RouterServiceStub(object):
    """===========================================================================
    RouterService  —  Endpoint Agent → Routing System
    Unidirectional client-streaming: agent streams chunks, router acks at end.
    ===========================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamPayload = channel.stream_unary(
                '/stegnar.RouterService/StreamPayload',
                request_serializer=stegnar__pb2.PayloadChunk.SerializeToString,
                response_deserializer=stegnar__pb2.StreamAck.FromString,
                _registered_method=True)


class RouterServiceServicer(object):
    """===========================================================================
    RouterService  —  Endpoint Agent → Routing System
    Unidirectional client-streaming: agent streams chunks, router acks at end.
    ===========================================================================
    """

    def StreamPayload(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamPayload': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamPayload,
                    request_deserializer=stegnar__pb2.PayloadChunk.FromString,
                    response_serializer=stegnar__pb2.StreamAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stegnar.RouterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stegnar.RouterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RouterService(object):
    """===========================================================================
    RouterService  —  Endpoint Agent → Routing System
    Unidirectional client-streaming: agent streams chunks, router acks at end.
    ===========================================================================
    """

    @staticmethod
    def StreamPayload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/stegnar.RouterService/StreamPayload',
            stegnar__pb2.PayloadChunk.SerializeToString,
            stegnar__pb2.StreamAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AnalysisServiceStub(object):
    """===========================================================================
    AnalysisService  —  Routing System → MITM Gateway
    Router dispatches a carved image; gateway returns CALPA-NET result.
    ===========================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeImage = channel.unary_unary(
                '/stegnar.AnalysisService/AnalyzeImage',
                request_serializer=stegnar__pb2.AnalysisRequest.SerializeToString,
                response_deserializer=stegnar__pb2.AnalysisResult.FromString,
                _registered_method=True)


class AnalysisServiceServicer(object):
    """===========================================================================
    AnalysisService  —  Routing System → MITM Gateway
    Router dispatches a carved image; gateway returns CALPA-NET result.
    ===========================================================================
    """

    def AnalyzeImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeImage': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeImage,
                    request_deserializer=stegnar__pb2.AnalysisRequest.FromString,
                    response_serializer=stegnar__pb2.AnalysisResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stegnar.AnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stegnar.AnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalysisService(object):
    """===========================================================================
    AnalysisService  —  Routing System → MITM Gateway
    Router dispatches a carved image; gateway returns CALPA-NET result.
    ===========================================================================
    """

    @staticmethod
    def AnalyzeImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stegnar.AnalysisService/AnalyzeImage',
            stegnar__pb2.AnalysisRequest.SerializeToString,
            stegnar__pb2.AnalysisResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
