"""
====================================================================================================
  stegnar-agent · main.py — Advanced Endpoint Agent & Threat Detection Sensor
====================================================================================================

  SYSTEM INTERFACE & OPERATIONAL TOPOLOGY:
  ----------------------------------------
  The Endpoint Agent acts as the lightweight user-space daemon deployed across monitored victim nodes.
  Its primary objective is low-footprint packet sniffing combined with out-of-band TLS session key
  extraction. Heavy computational operations (MIME inspection, decryption, CALPA steganalysis) are
  delegated to the privileged `stegnar-mitm` gateway.

  CONCURRENT ASYNC PIPELINES:
  --------------------------
  The agent runs 4 highly optimized, non-blocking asynchronous event loops:
  
    1. Sniffer (capture_loop): Sniffs raw network packets on `CAPTURE_IFACE` using Scapy/AsyncSniffer.
       Packets are tagged with high-resolution timestamps and queued.
    2. Key Extractor (watch_keylog): Tail-follows `SSLKEYLOGFILE` dynamically to extract symmetric TLS
       session keys generated by active browsers or applications.
    3. gRPC Client (stream_to_router): Streams queued packets and session keys in real-time to the
       Central Routing system using persistent HTTP/2 gRPC connections. Supports active backpressure.
    4. Heartbeat Daemon (heartbeat_loop): Regularly announces endpoint health, IP address, and status
       to the SOC dashboard api to register node enrollment immediately.

  SHUTDOWN BEHAVIOR:
  ------------------
  Responds gracefully to SIGINT and SIGTERM. On signal trigger, it stops all listeners, flushes
  buffers, cancels pending tasks, and disconnects the gRPC channel cleanly.
====================================================================================================
"""

import asyncio
import hashlib
import logging
import os
import pathlib
import signal
import socket as _sock
import time as _time

logging.basicConfig(
    level=os.environ.get("LOG_LEVEL", "INFO"),
    format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
)
logger = logging.getLogger("stegnar.agent")

from sniffer       import capture_loop, CapturedPacket
from key_extractor import watch_keylog
from grpc_client   import stream_to_router

IFACE          = os.environ.get("CAPTURE_IFACE",   "eth0")
CAPTURE_FILTER = os.environ.get(
    "CAPTURE_FILTER",
    "not port 50051 and not port 50052 and not port 8080 and not port 9000",
)
KEYLOG_PATH    = os.environ.get("SSLKEYLOGFILE",   "/tmp/ssl_keys.log")
ENDPOINT_ID    = os.environ.get("ENDPOINT_ID",      "unknown")
SOC_API_URL    = os.environ.get("SOC_API_URL",      "http://soc-api:3001")
QUEUE_SIZE     = 1000


async def heartbeat_loop(stop_event: asyncio.Event):
    """
    Sends a heartbeat POST to the SOC API every 15s so endpoint_registry
    is populated immediately — even before the first gRPC cycle completes.
    """
    import urllib.request, json as _json
    url = f"{SOC_API_URL}/api/agents/heartbeat"

    # Resolve own IP
    try:
        my_ip = _sock.gethostbyname(_sock.gethostname())
    except Exception:
        my_ip = "unknown"

    hb_no = 0
    while not stop_event.is_set():
        hb_no += 1
        try:
            body = _json.dumps({"endpoint_id": ENDPOINT_ID, "ip": my_ip}).encode()
            req  = urllib.request.Request(url, data=body, headers={"Content-Type": "application/json"}, method="POST")
            with urllib.request.urlopen(req, timeout=5) as resp:
                result = _json.loads(resp.read())
            logger.debug("[heartbeat] #%d → %s ok=%s", hb_no, url, result.get("ok"))
        except Exception as e:
            logger.warning("[heartbeat] #%d failed: %s", hb_no, e)

        try:
            await asyncio.wait_for(stop_event.wait(), timeout=15.0)
        except asyncio.TimeoutError:
            pass


async def main():
    stop_event = asyncio.Event()
    pkt_queue  = asyncio.Queue(maxsize=QUEUE_SIZE)
    key_queue  = asyncio.Queue(maxsize=QUEUE_SIZE)

    loop = asyncio.get_event_loop()

    def _handle_signal():
        logger.info("[Agent] Shutdown signal received.")
        stop_event.set()

    loop.add_signal_handler(signal.SIGTERM, _handle_signal)
    loop.add_signal_handler(signal.SIGINT,  _handle_signal)

    logger.info(
        "[Agent] Starting — id=%s iface=%s keylog=%s capture_filter=%s",
        ENDPOINT_ID, IFACE, KEYLOG_PATH, CAPTURE_FILTER,
    )

    tasks = [
        asyncio.create_task(capture_loop(IFACE, pkt_queue, stop_event, CAPTURE_FILTER), name="sniffer"),
        asyncio.create_task(watch_keylog(KEYLOG_PATH, key_queue, stop_event),   name="key-extractor"),
        asyncio.create_task(stream_to_router(pkt_queue, key_queue, stop_event), name="grpc-stream"),
        asyncio.create_task(heartbeat_loop(stop_event),                         name="heartbeat"),
    ]

    # Wait for ALL tasks (or stop_event) — not FIRST_EXCEPTION
    await stop_event.wait()

    logger.info("[Agent] Stopping all tasks...")
    for t in tasks:
        t.cancel()
    await asyncio.gather(*tasks, return_exceptions=True)
    logger.info("[Agent] Endpoint Agent stopped cleanly.")


if __name__ == "__main__":
    asyncio.run(main())
